// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSZ7VGQHZCdekU2L70-5vx20Sqkfe9oOk',
    appId: '1:169850125671:web:44e8b08089acb3565503c2',
    messagingSenderId: '169850125671',
    projectId: 'pkl-attendance',
    authDomain: 'pkl-attendance.firebaseapp.com',
    storageBucket: 'pkl-attendance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojG3TaXSFGJbmVGAjuOHYhnHhB0KJMhI',
    appId: '1:169850125671:android:675e2483f0c9bfc65503c2',
    messagingSenderId: '169850125671',
    projectId: 'pkl-attendance',
    storageBucket: 'pkl-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPto5IcWNIH3m6OlsxW3fTj9Tw71uoXRQ',
    appId: '1:169850125671:ios:756d14bad50463c75503c2',
    messagingSenderId: '169850125671',
    projectId: 'pkl-attendance',
    storageBucket: 'pkl-attendance.firebasestorage.app',
    iosBundleId: 'com.example.pklAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPto5IcWNIH3m6OlsxW3fTj9Tw71uoXRQ',
    appId: '1:169850125671:ios:756d14bad50463c75503c2',
    messagingSenderId: '169850125671',
    projectId: 'pkl-attendance',
    storageBucket: 'pkl-attendance.firebasestorage.app',
    iosBundleId: 'com.example.pklAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSZ7VGQHZCdekU2L70-5vx20Sqkfe9oOk',
    appId: '1:169850125671:web:0ad5fcce806e4b585503c2',
    messagingSenderId: '169850125671',
    projectId: 'pkl-attendance',
    authDomain: 'pkl-attendance.firebaseapp.com',
    storageBucket: 'pkl-attendance.firebasestorage.app',
  );
}
